language: python
python:
    - "2.7"

# The version of SWIG packaged with the TravisCI VM's (2.0.4) doesn't work for us
# - sudo apt-get install -qq swig
before_install:
    - sudo add-apt-repository -y ppa:webupd8team/java # for the oracle jdk
    - sudo apt-get update -qq
    - sudo apt-get install -y libpcre3-dev oracle-java8-installer ant junit4 
    - wget http://prdownloads.sourceforge.net/swig/swig-3.0.2.tar.gz -O - | tar xzf -
    - (cd swig-3.0.2/ && ./configure -prefix=$HOME --without-alllang --with-python && make -j 2 && make install) >/dev/null
    - export PATH=$HOME/bin:$PATH
    - swig -version
    - ulimit -a
    - export INSTALLDIR="${HOME}/stuff"
    - export LocalPyInstallPath="${INSTALLDIR}/lib/python2.7/site-packages/"
    - export PYTHONPATH="${LocalPyInstallPath}:$PYTHONPATH"

install:
    - make clean all
    - mkdir -p "${LocalPyInstallPath}"
    - (cd bindings/pyrapi && python setup.py install --prefix "${INSTALLDIR}" --skip-build)

script:
    - python bindings/pyrapi/tests/test_pyrapi.py
    - (cd bindings/jrapi && ant run-tests)
