language: python
python:
    - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq swig
    - tests/ci/setup_bwa.sh bwa-build
    - export BWA_PATH=bwa-build

install: make clean all

script: python tests/pyrapi/test_pyrapi.py
